### ISSUE TITLE
State can get initial value from parent Component?

### ISSUE THREAD

**Issue by demns** [uberVU/react-guide#10]
I have another question about the table:

| - | _props_ | _state_ |
| --- | --- | --- |
| Can get initial value from parent Component? | **Yes** | Yes |
| Can be changed by parent Component? | Yes | No |
| ... | ... | ... |

While I can understand that with getInitialState (and constructors in es6) I can set the initial state based just on the parent's value, it's still one more step to do**. Even more, [here](https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html) it's stated that in the majority of simple cases having props in getInitialState is an anti-pattern.

I cannot get the main idea of this **yes** and to my mind it's pretty confusing, so I'm asking for help. What am I missing here?

**What I mean by "one more step" is:
`<Button color={'red'}>`
... 
// and in the button component
`this.props.color`
But how can I do the same with state?

**Comment by NiGhTTraX** [comment]
> Even more, here it's stated that in the majority of simple cases having props in getInitialState is an anti-pattern.

It's an anti-pattern because if you set initial state using props, then you might have to resync it when new props come in. This is an indication that the props are the source of truth and that your component shouldn't hold state.

``` jsx
class C extends React.Component {
  constructor(props) {
    this.state = {
      foo: this.props.foo
    };
  }
  render() {
    return <div>{this.state.foo}</div>;
  }
}

ReactDOM.render(<C foo="bar" />, container);
ReactDOM.render(<C foo="baz" />, container);
```

The problem with the above is that you will probably expect `"baz"` to be rendered, but instead you'll get `"bar"` because that's the current state of the component and it wasn't updated when new props came in.

To fix that you can implement the `componentWillReceiveProps` method:

``` jsx
class C extends React.Component {
  constructor(props) {
    this.state = {
      foo: this.props.foo
    };
  }
  render() {
    return <div>{this.state.foo}</div>;
  }
  componentWillReceiveProps(nextProps) {
    // This is a code smell. It's telling you that the props are more
    // important than the state and that you should lose one of them.
    this.setState({ foo: nextProps.foo });
  }
}
```

Did that answer your question?

**Comment by demns** [comment]
@NiGhTTraX Andrei, thank you for your answer. What I actually meant is that you cannot automatically assign state value in the child component from the parent, the thing that you can do with props (without additional steps, of course). It was a bit confusing for me, but now I can understand that having **yes** in the table doesn't necessarily mean that it is done by React :)
