### ISSUE TITLE
Are props geometrical properties of a component?

### ISSUE THREAD

**Issue by cognominal** [uberVU/react-guide#2]
Are they? are they only that?
Are they calculated during the  graphical rendering by the browser?
Question from someone new to react, digging in atom sources, and seing @props all over the place and googling his way to your guide.
Nor sure how to submit a question so filed it as an issue. Sorry about that.
Thx for that document.

**Comment by cognominal** [comment]
Oops, i see they are the input of the render function

**Comment by ovidiuch** [comment]
Props are just generic options for a component, raw JS data types. Make sure to read the React.js docs before this guide: http://facebook.github.io/react/docs/getting-started.html – These are just some best practices on top understanding the mechanics of React
