### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by phillbaker** [uberVU/react-guide#3]
I found this [table](https://github.com/uberVU/react-guide/blob/master/props-vs-state.md#changing-props-and-state) discussing the differences between props and state to be extremely helpful! Thanks for putting this guide together.

I've submitted a copy of the table to the official react docs, but I wanted to clarify the licensing. Is there a specific license under which your guide is available?

**Comment by ovidiuch** [comment]
Don't worry about the license, feel free to post it anywhere. Linking to the original is preferable, of course.
